#!/bin/bash

# colors
BASH_COLOR='\033[1;33m'
ZSH_COLOR='\033[1;34m'

# check if the shell is zsh or bash
if [ -n "$ZSH_VERSION" ]; then
    echo -e "${ZSH_COLOR} zsh detected"
    echo "" >> ~/.zshrc
    source ~/.zshrc
else
    echo -e "${BASH_COLOR} bash detected"
    echo "" >> ~/.bashrc
    source ~/.bashrc
fi