#!/bin/bash


# curl the latest version of the script

curl https://raw.githubusercontent.com/MatteoKrsticDev/gsh/main/versions/current.txt >> tempVersion.txt
 

if [ "$(cat tempVersion.txt)" == "$(cat current.txt)" ]; then
    echo "You are already using the latest version of gsh"
    rm tempVersion.txt
else
    echo "Updating gsh"
    git fetch 
    git pull
    clear
    echo "gsh updated"
fi