#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

# Check gsh version
checkVersion() {}

# Main functions
addLine() {
    existFile
    if [ $1 == "" ]; then echo -e "${RED}[ERR]${NC} No file name provided"; exit 1; fi
    url="https://raw.githubusercontent.com/MatteoKrsticDev/gsh/main/resources/$1.gitignore"
    if [ $(curl $url) = "404: Not Found"]; then echo -e "${RED}[ERR]${NC} File not found"; exit 1; fi
    content=$(curl $url | sed 's/\r//g') 
    echo "### $1.gitignore ###\n\n$content\n" >> .gitignore
    echo -e "${GREEN}[OK]${NC} $1.gitignore added to .gitignore"
}

existFile() {
    if [ -f ".gitignore" ]; then
        echo "${YELLOW}[IN]${NC} .gitignore exist, installing template"
    else
        read -p ".gitignore not found, do you want to create it? [y/n] " yn

        case $yn in
        [Yy]*)
            touch .gitignore
            echo -e "${GREEN}[OK]${NC} Creating .gitignore"
            echo -e "${YELLOW}[IN]${NC} continue with the installation..."
            ;;
        [Nn]*)
            echo -e "${RED}[ERR]${NC} Please create .gitignore manually or use gsh init"
            exit 1
            ;;
        *)
            touch .gitignore
            echo -e "${GREEN}[OK]${NC} Creating .gitignore"
            echo -e "${YELLOW}[IN]${NC} I continue with the installation..."
            ;;
        esac
    fi
}

# Check commands
case $1 in
"add" | "a")
    existFile
    addLine $2
    ;;
"init" | "i")
    if [ -f ".gitignore" ]; then
        echo -e "${RED}[ERR]${NC} You already have a .gitignore file"
        exit 1
    else
        touch .gitignore
        echo -e "${GREEN}[OK]${NC} Creating .gitignore"
    fi
    ;;

*)
    echo -e "Usage: $0 {addLine|existFile|addCustom|removeCustom}"
    ;;
esac
