#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

# Check gsh version
checkVersion() {}

# Main functions
addLine() {
    existFile
    if [ $1 == "" ]; then echo -e "${RED}Error:${NC} No file name provided"; exit 1; fi
    content=$(curl )
}

existFile() {
    if [ -f ".gitignore" ]; then
        echo "${YELLOW}.gitignore exist, installing template${NC}"
    else
        read -p ".gitignore not found, do you want to create it? [y/n] " yn

        case $yn in
        [Yy]*)
            touch .gitignore
            echo "${GREEN}Creating .gitignore${NC}"
            echo "${YELLOW}I continue with the installation...${NC}"
            ;;
        [Nn]*)
            echo "${RED}Please create .gitignore manually or use gsh init${NC}"
            exit 1
            ;;
        *)
            touch .gitignore
            echo "${GREEN}Creating .gitignore${NC}"
            echo "${YELLOW}I continue with the installation...${NC}"
            ;;
        esac
    fi
}

# Check commands
case $1 in
"add" | "a")
    existFile
    ;;
"init" | "i")
    if [ -f ".gitignore" ]; then
        echo "${RED}You already have a .gitignore file${NC}"
        exit 1
    else
        touch .gitignore
        echo "${GREEN}Creating .gitignore${NC}"
    fi
    ;;

*)
    echo -e "Usage: $0 {addLine|existFile|addCustom|removeCustom}"
    ;;
esac
